

---

apiVersion: v1
kind: Secret
metadata:
  name: bigip-login
  namespace: kube-system
stringData:
  password: P@ssw0rd123
type: Opaque

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bigip-kubernetes-gateway-controller-configmap
  namespace: kube-system
data:
  bigip-kubernetes-gateway-config: |
    - management:
        username: admin
        ipAddress: 10.250.11.186
        port: 443

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigip-kubernetes-gateway-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigip-kubernetes-gateway-controller-pod
  template:
    metadata:
      name: bigip-kubernetes-gateway-controller-pod
      labels:
        app: bigip-kubernetes-gateway-controller-pod
    spec:
      serviceAccountName: k8s-bigip-ctlr
      nodeSelector:
        # node-role.kubernetes.io/control-plane: "true"
        # node-role.kubernetes.io/master: "true"
      containers:
        # kubectl logs -f deployment/bigip-kubernetes-gateway-controller -n kube-system
        - name: bigip-kubernetes-gateway-controller-pod
          # image: f5devcentral/bigip-kubernetes-gateway:v0.2.1-20230411
          # image: zongzw/bigip-kubernetes-gateway:latest-20230317-150818
          # image: zongzw/bigip-kubernetes-gateway-controller:latest-20231127-213249
          image: zongzw/bigip-kubernetes-gateway-controller:latest-20231221-214041
          imagePullPolicy: IfNotPresent
          command: ["/bigip-kubernetes-gateway-controller-linux"]
          args: [
            "--controller-name=f5.io/gateway-controller-name",
            "--bigip-config-directory=/bigip-config",
            "--bigip-credential-directory=/bigip-credential"
          ]
          volumeMounts:
            - name: bigip-credential
              mountPath: /bigip-credential
              readOnly: true
            - name: bigip-config
              mountPath: /bigip-config
              readOnly: true
      volumes:
        - name: bigip-credential
          secret:
            secretName: bigip-login
        - name: bigip-config
          configMap:
            name: bigip-kubernetes-gateway-controller-configmap
---

# expose the Prometheus port with NodePort
apiVersion: v1
kind: Service
metadata:
  name: bigip-kubernetes-gateway-controller
  namespace: kube-system
spec:
  selector:
    app: bigip-kubernetes-gateway-controller-pod
  ports:
    - name: bigip-kubernetes-gateway-controller-metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: bigip-kubernetes-gateway-controller-health
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
